### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by cor3ntin** [Mobsya/scratch-vm#1]
upstream uses transifex to translates scratch

I suggest we do the same

Rough idea:
- 1 In the code, use https://www.npmjs.com/package/format-message (as the rest of scratch) to format translatable text
- Modify package.json to extract thymio-specific in a separate files
- Create an account transifex or similar service
- Push the generated file on said service
- translate...
- sync trads

**Comment by mbonani** [comment]
we use a service for mobsya website @Vincebecker  is that compatible?

**Comment by cor3ntin** [comment]
So, unless we also fork  `scratch-l10n`, there is apparently no extension point for translations yet ( despite what the example claim) - see https://github.com/LLK/scratch-gui/issues/3139

So we need to either
- fork https://github.com/LLK/scratch-l10n - I really want to avoid doing that
- find a way to plug into react-intl somewhow
- wait for upstream to provide the missing facility

**Comment by Vincebecker** [comment]
@mbonani The service is called Weglot (https://weglot.com). There are different way to use it so I let @cor3ntin  take a look (https://weglot.com/fr/documentation/getting-started)

Paolo once talked about https://www.deepl.com/api.html maybe it's worth to take a look at it too.

**Comment by mbonani** [comment]
actually we made a branch to have bloc in french 
we should wait until more info come from https://github.com/LLK/scratch-vm/issues/645#issuecomment-425997487

**Comment by mbonani** [comment]
Translation mecanim is done. Translation is done in EN,IT,FR

**Comment by mbonani** [comment]
Missing DE

**Comment by mbonani** [comment]
get several version of DE, should be review

**Comment by cbarraud** [comment]
I received the Arabic translation from our reseller in Israel: 
[SCRATCH3_AR.txt](https://github.com/Mobsya/scratch-vm/files/3441019/SCRATCH3_AR.txt)

If we can include that, that would be perfect.

**Comment by mbonani** [comment]
included
