### ISSUE TITLE
icon is double on the left

### ISSUE THREAD

**Issue by mbonani** [Mobsya/scratch-vm#2]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_
![image](https://user-images.githubusercontent.com/1000934/45666998-a1eb6280-bb17-11e8-9886-2f56c8e67bba.png)

### Operating System and Browser

_e.g. Win 10  Chhrome  69.0.3497.92 (Build officiel)

**Comment by Vincebecker** [comment]
If you can use CSS :

Change

`background-image: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiP…Z2LTFWMC44QzIwLDAuNCwxOS42LDAsMTkuMiwwTDE5LjIsMHoiLz4NCjwvZz4NCjwvc3ZnPg0K);`

to

`background: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiP…Z2LTFWMC44QzIwLDAuNCwxOS42LDAsMTkuMiwwTDE5LjIsMHoiLz4NCjwvZz4NCjwvc3ZnPg0K) no-repeat center;`

**Comment by Vincebecker** [comment]
Change svg with the following :

`url('data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAyMi4xLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjxzdmcgdmVyc2lvbj0iMS4xIiBpZD0iTGF5ZXJfMSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4IiB5PSIwcHgiDQoJIHZpZXdCb3g9IjAgMCAyOTEuNyAyOTEuNyIgc3R5bGU9ImVuYWJsZS1iYWNrZ3JvdW5kOm5ldyAwIDAgMjkxLjcgMjkxLjc7IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxzdHlsZSB0eXBlPSJ0ZXh0L2NzcyI+DQoJLnN0MHtmaWxsOiM5RDlEOUM7fQ0KCS5zdDF7ZmlsbDojRDNEM0QzO30NCgkuc3Qye2ZpbGw6I0VGRUZFRjt9DQoJLnN0M3tmaWxsOiMwMjAyMDM7fQ0KPC9zdHlsZT4NCjxwYXRoIGNsYXNzPSJzdDAiIGQ9Ik0yNzkuMiw4N0gxMi4zQzUuOSw4NywwLjcsOTIuMiwwLjcsOTguNnYxMDUuNGMwLDYuNCw1LjIsMTEuNywxMS43LDExLjdoMjYuMmMxMi40LDEyLjgsMjkuNSwyMC4xLDQ3LjQsMjAuMQ0KCXMzNC45LTcuMyw0Ny40LTIwLjFIMjE4YzMuMSwxMC45LDEzLDE4LjcsMjQuOCwxOC43YzExLjgsMCwyMS43LTcuOCwyNC44LTE4LjdoMTEuNmM2LjQsMCwxMS43LTUuMiwxMS43LTExLjdWOTguNg0KCUMyOTAuOSw5Mi4yLDI4NS42LDg3LDI3OS4yLDg3eiIvPg0KPGc+DQoJPGVsbGlwc2UgY2xhc3M9InN0MSIgY3g9IjI0Mi44IiBjeT0iMjA4LjYiIHJ4PSIxOS4zIiByeT0iMTkuNCIvPg0KCTxwYXRoIGNsYXNzPSJzdDIiIGQ9Ik0yNzkuMiwyMDkuMkgxMi4zYy0yLjksMC01LjItMi4zLTUuMi01LjJWOTguNmMwLTIuOSwyLjMtNS4yLDUuMi01LjJoMjY2LjljMi45LDAsNS4yLDIuMyw1LjIsNS4ydjEwNS40DQoJCUMyODQuNCwyMDYuOSwyODIuMSwyMDkuMiwyNzkuMiwyMDkuMnoiLz4NCgk8Y2lyY2xlIGNsYXNzPSJzdDIiIGN4PSI4NS45IiBjeT0iMTY5LjgiIHI9IjU0LjMiLz4NCgk8cGF0aCBjbGFzcz0ic3QzIiBkPSJNODUuOSwyMjkuM2MtMzIuOCwwLTU5LjUtMjYuNy01OS41LTU5LjVzMjYuNy01OS41LDU5LjUtNTkuNXM1OS41LDI2LjcsNTkuNSw1OS41UzExOC43LDIyOS4zLDg1LjksMjI5LjN6DQoJCSBNODUuOSwxMjAuOGMtMjcsMC00OSwyMi00OSw0OXMyMiw0OSw0OSw0OXM0OS0yMiw0OS00OVMxMTIuOSwxMjAuOCw4NS45LDEyMC44eiIvPg0KCTxwYXRoIGNsYXNzPSJzdDMiIGQ9Ik0yMzQuMiwxNTQuM2gtMjYuN2MtMC44LDAtMS41LTAuNy0xLjUtMS41di0xMS41YzAtMC44LDAuNy0xLjUsMS41LTEuNWgyNi43YzAuOCwwLDEuNSwwLjcsMS41LDEuNXYxMS41DQoJCUMyMzUuNywxNTMuNiwyMzUuMSwxNTQuMywyMzQuMiwxNTQuM3oiLz4NCgk8cGF0aCBjbGFzcz0ic3QzIiBkPSJNMjg0LjQsMTM5LjhoLTEzYy0xLDAtMS45LDAuOC0xLjksMS45djEwLjhjMCwxLDAuOCwxLjksMS45LDEuOWgxM1YxMzkuOHoiLz4NCjwvZz4NCjwvc3ZnPg0K');
`

**Comment by mbonani** [comment]
perfect it work, it will be soon online
