### ISSUE TITLE
blocks with several sensors should have the checks box to visualize them

### ISSUE THREAD

**Issue by mbonani** [Mobsya/scratch-vm#3]
the blocks of several variable like proximity h, proximity ground add a check box on scratch X, it should be there otherwise there are not usefull

**Comment by mbonani** [comment]
![image](https://user-images.githubusercontent.com/1000934/45974568-017ace00-c042-11e8-88c2-82878d5145a9.png)

i do not find where it is define wich blocks have this check box or not

**Comment by mbonani** [comment]
my understanding is the checkbox are automaticaly shown when variable blocks are not blocking and have no parameters. It is not something that is controled by the definition of the block. It seems this feature is note working anymore on extensions

**Comment by Vincebecker** [comment]
You can click on it to view the value but the values are updated only when you click on it again.
![image](https://user-images.githubusercontent.com/10742038/45998854-5f400200-c0a4-11e8-8062-b41c3a828c86.png)

Also to display the values on the scratch screen you can do this :

![image](https://user-images.githubusercontent.com/10742038/45999019-cc539780-c0a4-11e8-8856-64d21694702d.png)

and here the values are updated when it changes

**Comment by mbonani** [comment]
fix in last development of scratch-vm
