### ISSUE TITLE
Delete multiple blocks not working

### ISSUE THREAD

**Issue by paolorossetti** [Mobsya/scratch-vm#39]
### Expected Behavior
When multiple blocks are on the work area I select them and I can move them together. When I press the right button on the mouse a pop-up window menu opens and I select to delete all the blocks selected. I expect the blocks to be deleted. 

### Actual Behavior

The blocks are not deleted

### Steps to Reproduce

put any block into the work area. Select 2 or more blocks. Right clic on the mouse. Press delete N blocks (where N is the number of blocks you selected) and you see that nothing is done.

### Operating System and Browser

Mac OSX High Sierra 10.13.6 - Firefox Quantum 66.0.3

**Comment by mbonani** [comment]
it is working with me, there is a pop up message that ask to confirm
