### ISSUE TITLE
Scratch 3 Sprite screen bugged

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/scratch-vm#43]
### Expected Behavior

I was programming something, displaying some variable on the Sprite screen (where there is the cat) and suddenly the screen blue-screened as below

### Actual Behavior

![image](https://user-images.githubusercontent.com/4930020/61038627-a0a06480-a3cd-11e9-8bba-ee2576f0ffb2.png)
I tried to go full screen to press the refresh button but it did not work. Loading a new program, a blank one or changing the language didn't fix the problem. Reloading Scratch completely fixed the issue.

### Steps to Reproduce

Apparently these specific things don't work: 
![image](https://user-images.githubusercontent.com/4930020/61039545-3ee0fa00-a3cf-11e9-90aa-a87bacd65c8d.png)
![image](https://user-images.githubusercontent.com/4930020/61043442-92a31180-a3d6-11e9-90c5-a7b092b1e7f0.png)
![image](https://user-images.githubusercontent.com/4930020/61048079-2b3e8f00-a3e1-11e9-93ee-ab4e1ea4833c.png)
![image](https://user-images.githubusercontent.com/4930020/61048164-5e811e00-a3e1-11e9-8aed-f45e7b5503e9.png)

These work fine: 
![image](https://user-images.githubusercontent.com/4930020/61039624-69cb4e00-a3cf-11e9-9541-e6527e551300.png)
![image](https://user-images.githubusercontent.com/4930020/61039684-89627680-a3cf-11e9-99b3-bdf46dfd24cd.png)
![image](https://user-images.githubusercontent.com/4930020/61048144-532df280-a3e1-11e9-8fcf-9ef89c362e37.png)

It's really when you press the refresh button that the sprite zone go blue-screen:
![image](https://user-images.githubusercontent.com/4930020/61048265-a9029a80-a3e1-11e9-8251-35295b9a1c36.png)

### Operating System and Browser

Windows 8.1, Version Thymio Suite Beta 2 online on thymio.org (2.0.0-350ce8fc BETA)

**Comment by mbonani** [comment]
it is something also reported by mooc (https://moocthymio.inria.fr/t/capteurs-distance-et-angle-imbriques/982) 
working: prox ground motor speed and inclinaison
not working: distance angle sound level odometer 

 it work for if you use say:
![image](https://user-images.githubusercontent.com/1000934/62112848-d2616880-b2b3-11e9-999e-68c0dfc15d84.png)

or an operator + 0: 
![image](https://user-images.githubusercontent.com/1000934/62113157-60d5ea00-b2b4-11e9-9859-be85759046b3.png)
