### ISSUE TITLE
Scratch 3 odometer need rework on initialisation & intuitivity

### ISSUE THREAD

**Issue by cbarraud** [Mobsya/scratch-vm#44]
I tried the Odometer block which has three parameters Direction, X and Y. 

The Direction is odd. If you use the Set odometer block and put a value as init, the value of the odometer Angle block will be 1 or 2 below the init value and then, as soon as you rotate with the motors, the value jumps. I tried the following:

Set value: 0 => read value 176
Set value: 50 => read value 126
Set value 100 => read value 76
Set value 200 => read value -24

Then, it seems that the 0 value of the direction makes the robot face the minus Y axis. In my opinion, it would be more intuitive to have the robot face the + X values.
![image](https://user-images.githubusercontent.com/4930020/61041125-21615f80-a3d2-11e9-9005-b29955662af2.png)

The value of the Direction is defined on a range of -90 to 280 which I also find strange. If you just rotate and look at the values you get, it's like that. I would suggest either to have a 0 to 360 or -180 to 180.

Finally on the X and Y axes, the units are strange. On the general other blocks like "move ()" or the speed, we use mm or mm/s. Here is just a coupe of measures I did:

10 units of odometer  => ~5.5 cm
20 units of odometer => ~11cm

Should we use the same ~mm units we use for the rest, especially for the "move ()"? Otherwise, it will be very hard to use this odometer block.

### Operating System and Browser
Windows 8.1, Version Thymio Suite Beta 2 online on thymio.org (2.0.0-350ce8fc BETA)

**Comment by mbonani** [comment]
put -180 to 180 is the easiest to do, there is some rounding problems that can appear

**Comment by mbonani** [comment]
hi put -180 to 180, so x is now align to robot, now when for instance you turn 45 degree you expect that the odometre do the same? now it is inverted, turn 90 odometre show -90... is that normal, sometimes I am confusing with graduation

**Comment by rivet-rgb** [comment]
three figures for synthesis I've found according to you
![odometre-direction-align](https://user-images.githubusercontent.com/54538162/63696083-3e36e280-c81a-11e9-978d-ba531c74a9e5.png)

I suggest to keep then current angle orientation like scratch (clockwise) 
A problem subsist in the fact that actual measured angle is a quite différent from blocs
With one Thymio, i get 108° for 90° programmed  and 126° with an other one. But, theses offset
are reproductibles !
About distance, if i programm <avancer 100> I get 24,75 with recorder odometer, 11 cm with one robot and 11,5 cm with the other.
The distance depend also on speed. avancer (100)
- speed 10 give 11,6 cm for physical distance 
- speed 50 give 10.6 cm
- speed 500 give 9,5 cm

**Comment by mbonani** [comment]
> With one Thymio, i get 108° for 90° programmed and 126° with an other one. But, theses offset
> are reproductibles !

Yes this depend on real speed of the robots that are not abolute I had work on an improvment for that but I am still not satisfy with the result

> About distance, if i programm <avancer 100> I get 24,75 with recorder odometer, 11 cm with one robot and 11,5 cm with the other.

theorically should be 10cm.

> The distance depend also on speed. avancer (100)
> 
> speed 10 give 11,6 cm for physical distance
> speed 50 give 10.6 cm
> speed 500 give 9,5 cm

yes at speed 500 the robot is saturating and cannot follow this real speed

**Comment by mbonani** [comment]
I made improvement in the odometer so that values are the same of moving blocks, go forward 50 makes odometer go forwards 50 and the same for angles, there is still some imprecision because we use integers (rounding problem) . Also using 16bits make a compromise of the size of the integration that is around 1m.
